name: Test
on:
  workflow_call:
    inputs:
    secrets:
      webhook:
        required: true
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        description: "Tested Go version ${{ matrix.go-version }} on ${{ matrix.os }}"
        webhook: ${{ secrets.webhook }}
