name: Validate
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    uses: sksmith/note-server/.github/workflows/lint.yml@master
  security:
    uses: sksmith/note-server/.github/workflows/sec.yml@master
  test:
    uses: sksmith/note-server/.github/workflows/test.yml@master
  notify:
    name: Notification
    needs: [lint, security, test, deploy]
    uses: sarisia/actions-status-discord@v1
    if: always()
    with:
      username: Pull Request
      description: A pull request has been made
      webhook: ${{ secrets.DISCORD_WEBHOOK }}